services:
  postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: passworddb
      ports:
        - "5432:5432"
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@localhost.com
        PGADMIN_DEFAULT_PASSWORD: pgadminpassword
      ports:
      - "5050:80"
